// TEMPORARY DATA

export let role = "faculty";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FST",
    designation:"Assistant Professor"
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Assistant professor"
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Assistant professor"
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Assistant professor"
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/192341/pexels-photo-192341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Assistant professor"
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Associate professor"
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FST",
    designation:"Assistant professor",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/936623/pexels-photo-936623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Assistant professor"
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Assistant professor"
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/943474/pexels-photo-943474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    department: "FMC",
    designation:"Assistant professor"
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "23IUT0330014",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "LLB",
    semester: "1st",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "23IUT03314",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "MCA",
    semester: "2nd",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "23IUT033090",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "BCA",
    semester: "3rd",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "23IUT0330010",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "BTech(CSE)",
    semester: "5th",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "23IUT0330017",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/192341/pexels-photo-192341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "MTech",
    semester: "3rd",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "23IUT0330009",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "BTech(Mech)",
    semester: "5th",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "23IUT0330011",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "BA (eng)",
    semester: "1st",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "23IUT033054",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/936623/pexels-photo-936623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "Mathematics(hons)",
    semester: "3rd",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "23IUT0330018",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "Physics(hons)",
    semester: "5th",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "23IUT0330016",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/943474/pexels-photo-943474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    program: "BMLT",
    semester: "2nd",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 9,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    class: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 21,
    class: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    class: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    class: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    class: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    program: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    program: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 21,
    program: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    program: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 9,
    name: "6D",
    capacity: 20,
    program: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    semester: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    semester: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    semester: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    semester: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    semester: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    semester: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    semester: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    semester: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    semester: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 9,
    subject: "Chemistry",
    semester: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "CS437",
    course: "BCA",
    faculty: "Debjani Bhowmik",
    date: "2024-01-01",
  },
  {
    id: 2,
    subject: "Machine Learning",
    course: "MCA",
    faculty: "Arunangshu Paul",
    date: "2024-01-01",
  },
  {
    id: 3,
    subject: "Mathematical Computing",
    course: "BTech",
    faculty: "Sanjib Debnath",
    date: "2024-01-01",
  },
  {
    id: 4,
    subject: "Cloud Computing",
    course: "MCA",
    faculty: "Sukanya Saha",
    date: "2024-01-01",
  },
  {
    id: 5,
    subject: "MCAC225T",
    course: "BTech(civil)",
    faculty: "Aarti jain",
    date: "2024-01-01",
  },
  {
    id: 6,
    subject: "Quantum Physics",
    course: "Physics",
    faculty: "Amarendra Haldar",
    date: "2024-01-01",
  },
  {
    id: 7,
    subject: "CS502",
    course: "BCA",
    faculty: "Dhrubajyoti Kalita",
    date: "2024-01-01",
  },
  {
    id: 8,
    subject: "Geo physics",
    course: "Physics",
    faculty: "Debjani Rakshit",
    date: "2024-01-01",
  },
  {
    id: 9,
    subject: "Python Programming",
    course: "BTech",
    faculty: "Lois Lindsey",
    date: "2024-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    course: "Chem(hons)",
    faculty: "Yagnyaseene Sengupta",
    date: "2024-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    semester: "1A",
    teacher: "Anthony Boone",
    dueDate: "2024-01-01",
  },
  {
    id: 2,
    subject: "English",
    semester: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2024-01-01",
  },
  {
    id: 3,
    subject: "Science",
    semester: "3A",
    teacher: "Catherine Malone",
    dueDate: "2024-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    semester: "1B",
    teacher: "Willie Medina",
    dueDate: "2024-01-01",
  },
  {
    id: 5,
    subject: "Art",
    semester: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2024-01-01",
  },
  {
    id: 6,
    subject: "Music",
    semester: "5A",
    teacher: "Katharine Owens",
    dueDate: "2024-01-01",
  },
  {
    id: 7,
    subject: "History",
    semester: "6A",
    teacher: "Shawn Norman",
    dueDate: "2024-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    semester: "6B",
    teacher: "Don Holloway",
    dueDate: "2024-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    semester: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2024-01-01",
  },
  {
    id: 9,
    subject: "Chemistry",
    semester: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2024-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    semester: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    semester: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    semester: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    semester: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    semester: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    semester: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    semester: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    semester: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    semester: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Chemistry",
    semester: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2024-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    semester: "1A",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    semester: "2A",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    semester: "3A",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    semester: "4A",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    semester: "5A",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    semester: "1B",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    semester: "2B",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    semester: "3B",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    semester: "4B",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Sports Tournament",
    semester: "5B",
    date: "2024-01-01",
    startTime: "9:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    semester: "4A",
    date: "2024-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    semester: "3A",
    date: "2024-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    semester: "3B",
    date: "2024-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    semester: "6A",
    date: "2024-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    semester: "8C",
    date: "2024-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    semester: "2A",
    date: "2024-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    semester: "4C",
    date: "2024-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    semester: "4B",
    date: "2024-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    semester: "3C",
    date: "2024-01-01",
  },
  {
    id: 9,
    title: "About 1C Math Test",
    semester: "1C",
    date: "2024-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "CS505",
    allDay: false,
    start: new Date(2024, 9, 21, 9, 15),
    end: new Date(2024, 9, 21, 10, 5),
  },
  {
    title: "MCAC225P",
    allDay: false,
    start: new Date(2024, 9, 21,11, 5),
    end: new Date(2024, 9, 21,11, 55),
  },
  {
    title: "CS502",
    allDay: false,
    start: new Date(2024, 9, 22, 11, 5),
    end: new Date(2024, 9, 22, 11, 55),
  },
  {
    title: "CS505P",
    allDay: false,
    start: new Date(2024, 9, 22, 12, 55),
    end: new Date(2024, 9, 22, 14, 5),
  },
  {
    title: "MCAC225T",
    allDay: false,
    start: new Date(2024, 9, 23, 9, 15),
    end: new Date(2024, 9, 23, 10, 5),
  },
  {
    title: "CS502",
    allDay: false,
    start: new Date(2024, 9, 23, 10, 10),
    end: new Date(2024, 9, 23, 11, 0),
  },
  {
    title: "CS437",
    allDay: false,
    start: new Date(2024, 9, 23, 12, 0),
    end: new Date(2024, 9, 23, 12, 50),
  },
  {
    title: "MCAC225T",
    allDay: false,
    start: new Date(2024, 9, 24, 9, 15),
    end: new Date(2024, 9, 24, 10, 5),
  },
  {
    title: "CS505",
    allDay: false,
    start: new Date(2024, 9, 24, 10, 10),
    end: new Date(2024, 9, 24, 11, 0),
  },

  {
    title: "CS437",
    allDay: false,
    start: new Date(2024, 9, 24, 12, 0),
    end: new Date(2024, 9, 24, 12, 50),
  },
  {
    title: "CS505",
    allDay: false,
    start: new Date(2024, 9, 25, 9, 15),
    end: new Date(2024, 9, 25, 10, 5),
  },

  {
    title: "CS437",
    allDay: false,
    start: new Date(2024, 9, 25, 10, 10),
    end: new Date(2024, 9, 25, 11, 0),
  },
  {
    title: "CS502 ",
    allDay: false,
    start: new Date(2024, 9, 25, 11, 5),
    end: new Date(2024, 9, 25, 11, 55),
  },
  {
    title: "MCAC225T",
    allDay: false,
    start: new Date(2024, 9, 25, 12, 55),
    end: new Date(2024, 9, 25, 13, 45),
  },
];